### ISSUE TITLE
System.ObjectDisposedException: Cannot access a disposed object

### ISSUE THREAD

**Issue by MegaThorx** [zacbre/Socks5#20]
```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   at socks5.TCP.Client.DataReceived(IAsyncResult res) in \Socks5-master\socks5\socks5\TCP\Client.cs:line 57
```

Appears when I use the proxy with Firefox

**Comment by tomhatzer** [comment]
I've got the same problem. Basically every connection that's using SSL prints out this error message. How can we get this fixed? Can I provide you with sample code and/or more detailed error logs?

**Comment by tomhatzer** [comment]
@ThrDev do you possibly have an answer/fix for this error?

**Comment by ThrDev** [comment]
Hey there Tom,

Yes, sample code where the error happens would be fantastic. Also if you could list the same exact scenarios you are using, i.e what socks5 client you are using, what website(s) you are visiting, etc. This is so that I can more accurately reproduce the error to fix it.

Thanks!

**Comment by tomhatzer** [comment]
Hey @ThrDev ,

that's awesome! I've been bumping my head the last few days and weeks to get this bug fixed, but I'm not able to do it...

I've modified the PacketEditor solution to be command line (previous windows forms), removed all the windows forms code and replaced a few parts with cli output. I also added a whitelist functionality so a that domains/ips on the whitelist are not forwarded to another host.

Would it be possible to send you the code in private?

I'm setting the socks Proxy parameters for jvm and using Apache Http Client as client for the socks proxy. It's working for a few requests, but errors start coming in directly afterwards. I can send you more details in private then, if that's ok for you.

Thank you very much!

Best wishes
Tom

**Comment by ThrDev** [comment]
Of course.

If you'd like, upload them somewhere and shoot me an email: admin@thrdu.de

Thanks!

**Comment by tomhatzer** [comment]
Hey @ThrDev :)

I've sent you an e-mail with access data to my gitlab server :) If it didn't arrive in your inbox, please have a look at your spam folder.

Thank you very much!

Best wishes
Tom

**Comment by ThrDev** [comment]
Hey again @tomhatzer!

Sorry, I've been pretty busy this week. I will take a look at it over the next few days and determine the issue!

Thanks!

**Comment by ThrDev** [comment]
Hey @tomhatzer,

I've attempted to go through and debug this. There's a really odd race condition that happens with the bandwidth counter, so it's been removed in the following branch.

https://github.com/ThrDev/Socks5/tree/connection-fix

I'd love to rewrite this entire project from scratch, considering it was a few years ago I started working on this and there's a lot to be optimized with the project.

Let me know if this fixes it for you, if not, we can try some other things.

Thanks!

**Comment by MilesTFox** [comment]
I found the following in a different project with the same issue, added the following:


bool SocketConnected(Socket s)
        {
            bool part1 = s.Poll(1000, SelectMode.SelectRead);
            bool part2 = (s.Available == 0);
            if (part1 & part2)
            {//connection is closed
                return false;
            }
            return true;
 }

-----

Then in DataRecieved after

if(disposed)
  return;

I added

if (!SocketConnected((Socket)res.AsyncState))
  return;
